# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# 网址题头布局
title: My Personal Blog
subtitle: '不积跬步无以至千里'
description: 'First-year THU Ph.D Candidate'
keywords:
author: MaximeHu
language: zh_CN
timezone: ''

## 网址##
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://huhong12345.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks
date_format: YYYY-MM-DD # 日期时间格式
time_format: HH:mm:ss ## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

####目录####
source_dir: source # 资源文件夹
public_dir: public #存放生成的站点文件
tag_dir: tags  #标签文件夹
archive_dir: archives  #归档文件夹
category_dir: categories  #分类文件夹
code_dir: downloads/code  
i18n_dir: :lang
skip_render:
include: #	Hexo 默认会忽略隐藏文件和文件夹（包括名称以下划线和 . 开头的文件和文件夹，Hexo 的 _posts 和 _data 等目录除外）。通过设置此字段将使 Hexo 处理他们并将它们复制到 source 目录下。
exclude:  #Hexo 会忽略这些文件和目录
ignore:
default_category: uncategorized # 分类&标签
category_map:
tag_map:
##search: # 局部搜索
 ## path: search.xml
  ##field: all

# 文章写作
new_post_name: :title.md # 新文章文件名称
default_layout: post   #预设布局
titlecase: false # 
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:   #代码块高亮
  enable: true
  hljs: true
  #xinjia
  line_number: false
  auto_detect: false
  tab_replace: ''

# Hexo feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# 分页 # order_by: Posts order. (Order by date descending by default)
index_generator: 
  path: ''
  per_page: 12  #主页每页多少个标签
  order_by: -date
# 分页，为0表示关闭分页

per_page: 12   #归档每页多少个标签
pagination_dir: page
external_link:
  enable: true # 用新标签打开链接
  field: site # Apply to the whole site
  exclude: ''

# 拓展## Plugins: https://hexo.io/plugins/## Themes: https://hexo.io/themes/
theme: aria
meta_generator: true  # 为false不会izai头部插入该标签


# 自动生成sitemap
sitemap:
path: sitemap.xml

#  上传
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: 
    github: https://github.com/huhong12345/huhong12345.github.io
    coding: git@e.coding.net:MaximeHu/MaximeHu.git
  branch: master