# If a option has many sub-options, and it's optional, then give it a `enable` sub-option. If not optional, don't use `enable`.

menu:  ##菜单设置
- name: home
  link: /
  icon: <i class="fas fa-home"></i>
- name: archives
  link: archives/
  icon: <i class="fas fa-archive"></i>
- name: categories
  link: categories/
  icon: <i class="fas fa-th-list"></i>
- name: tags
  link: tags/
  icon: <i class="fas fa-tags"></i>
- name: about
  link: about/
  icon: <i class="fas fa-user-edit"></i>

# Transform your image to those favicons in https://realfavicongenerator.net/.
favicon:
  apple_touch_icon: favicons/apple-touch-icon.png
  android_chrome_large: favicons/android-chrome-192x192.png
  medium: favicons/favicon-32x32.png
  small: favicons/favicon-16x16.png
  safari_pinned_tab: favicons/safari-pinned-tab.svg
  android_manifest: favicons/site.webmanifest
  ms_browserconfig: favicons/browserconfig.xml
  fallback: favicons/favicon.ico

# Must be an array.
keywords:
  - Life
  - ARIA
  - Hexo

# https://creativecommons.org/licenses/
# by | by-sa | by-nd | by-nc | by-nc-sa | by-nc-nd
creative_commons:

# Available: atom-one-dark | atom-one-light | solarized-dark | solarized-light
highlight: atom-one-dark

#highlight: dark
# Custom info in footer.
custom_info: 托管于<i class="fab fa-github-alt"></i><a href="https://pages.github.com/" target="_blank">GitHub Pages</a>

# Select all your webfont in a CDN like Google Fonts, and then copy `href` property in the `<link>` tag, like `link: //fonts.googleapis.com/css?family=Lato|Roboto+Condensed|Skranji|Ubuntu|Ubuntu+Mono`.
# Then set different fonts to different parts here.
custom_font:
  enable: false
  link:
  all:
  title:
  subtitle:
  main:
  code:

#avatar: images/guidao3.jpg
avatar: images/guidao.jpg

logo: images/mylogo2.png

# Theme color.
# Need quote to prevent `#` from comment.
color: "#33363b"

google_verification: "OZLJPBF16hIAV-G24xvVKkFP0bYNbDLgW83PPvxBctk"

since:

search: true

# `left`, `right`, `false`
sidebar: left

# Animation in Home, Archive, Category and Tag.
animate: true

#busuanzi: true
busuanzi:
  enable: true

# If you want ARIA generate excerpt, set it to the length you want. If you don't, leave it blank.
# Recomend to place `<!--more-->` to where you want to stop excerpt in content instead of use this option.
# Example: `auto_excerpt: 200`, use first 200 chars in post content as excerpt.
auto_excerpt: 320
##每个博客在首页的字符数。
##也可在每个博客里使用 <!--more--> 停止

# If you want to use MathJax, first fill a CDN link like `cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=TeX-MML-AM_CHTML`, then set `enable: true`.
# And set front-matter `mathjax: true` to the page you want to use it.
# You can also set `global: true` here to load MathJax in all pages.
# But it's not recommended because MathJax sources are too large, that's why ARIA doesn't contain them and ask for CDN.
mathjax:
  enable: true
  per_page: false
  #global: true
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  #cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Note: `fontawesome` is fontawesome-all. `scrollspy` and `util` are from bootstrap. `busuanzi` is `busuanzi.pure.mini.js`.
# If you don't know what you are doing, don't change it.
lib_cdn:
  enable: false
  jquery:
  fontawesome:
  scrollspy:
  util:
  lightgallery:
    js:
    css:
  lg_fullscreen:
  lg_hash:
  lg_pager:
  lg_thumbnail:
  lg_zoom:
  busuanzi:
  atom-one-dark:
  atom-one-light:
  solarized-dark:
  solarized-light:
  normalize:
  search:
  marked:
  timeago:
  commentjs:
    js:
    css:
  av_min:
  valine:
  clipboard:

social:
  enable: true
  links:
    - name:  huhong.thu@gmail.com
      link: mailto:huhong.thu@gmail.com
      icon: <i class="fas fa-envelope"></i>
    - name:  MaximeHu
      link: https://github.com/huhong12345
      icon: <i class="fab fa-github"></i>
    - name:  少临
      link: https://www.zhihu.com/people/maximehu
      icon: <i class="fab fa-zhihu"></i>

blogroll:
  enable: true
  links:
    - name: Library
      link: https://lib.tsinghua.edu.cn/
      icon: <i class="fas fa-link"></i>
    - name: Services
      link: https://thu.services/services/
      icon: <i class="fas fa-link"></i>
    - name: Runood
      link: https://www.runoob.com/python3/python3-data-type.html
      icon: <i class="fas fa-link"></i>

# `comment.commentjs.type`: Choose between `github` and `oschina`.
comment:
  enable: true
  disqus_shortname:
  commentjs:
    enable: true
    type: "github"
    user: "huhong12345"
    repo: "huhong12345.github.io"
    client_id: 553c59d0dc113422c1c6
    client_secret: dd4d567e2c3038605681e28135d4a4265fd77b03
  valine:
    enable: false
    app_id:  #PSzi1vc4OfAJuYaVAw4CLjqi-gzGzoHsz
    app_key: #nJfplkzB7gSwSByQn3y8CeD4
    verify: false
    notify: false
    avatar: mm
    meta: "[\"nick\", \"mail\", \"link\"]"
    page_size: 10
    lang: zh-cn
    visitor: false
    highlight: true
    avatar_force: false

#reward:
 # enable: false
  #comment: 虽然不会有人，但功能还是要加上的~
   #wechatpay_qrcode: images/wechat.jpg
   #alipay_qrcode: 
  # bitcoin_qrcode: 

# Google Analytics Tracking ID
google_analytics:
